### ISSUE TITLE
Create website

### ISSUE THREAD

**Issue by suriyaa** [opensourcecities/munich#8]
Create website:

- [x] With [Bunto](https://buntowaf.tk/) and [Jekyll](https://jekyllrb.com/)
- [x] Deploy with @traviscibot to [GitHub Pages](https://pages.github.com/)
- [x] Website domain: [`opensourcecities.github.io/munich`](https://opensourcecities.github.io/munich/)

**Comment by suriyaa** [comment]
✅ Published at https://github.com/opensourcecities/munich/commit/bfcf57951b513a11502126bdac1af044b664e5df!

**Comment by suriyaa** [comment]
Visit website at https://opensourcecities.github.io/munich/.

<blockquote><div>munich</div><div><strong><a href="https://opensourcecities.github.io/munich/">Open Source Munich</a></strong></div><div>:beer: Open Source Cities: Munich (Germany)!</div></blockquote>

**Comment by suriyaa** [comment]
:white_check_mark: Done. :tada:

**Comment by RichardLitt** [comment]
Woo!

**Comment by khos2ow** [comment]
Nice! Munich!
I'll say we should proceed with existing theme we have.
